<html>
 <head></head>
 <body>
  <p><strong>Подвиг 6.</strong> Имеется следующий фрагмент программы:</p> 
  <pre><code>try:
&nbsp; &nbsp; x, y = map(float, input().split())
&nbsp; &nbsp; d = x / y
except ZeroDivisionError:
&nbsp; &nbsp; print('ZeroDivisionError')
except:
&nbsp; &nbsp; print('except')</code></pre> 
  <p>В каких случаях выполнение программы перейдет во второй блок except?</p>
 </body>
</html>